name: Deploy Validation and Analysis
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]
    push:
        branches:
            - main
jobs:
    deploy:
        name: ValidateSource
        runs-on: 'ubuntu-latest'
        container: salesforce/salesforcedx:latest-rc-full
        steps:
            - name: Clone Repository (Latest)
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.ref }}

            - name: 'Populate auth file with DevHub secret'
              shell: bash
              run: |
                  echo ${{ secrets.DEVHUB_KEY}} > ./DEVHUB_KEY.txt
                  secretFileSize=$(wc -c "./DEVHUB_KEY.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing DEVHUB_KEY secret.";
                      exit 1;
                  fi

            - name: 'Authenticate DevHub'
              run: sfdx auth:sfdxurl:store -f ./DEVHUB_KEY.txt -a devhub

            - name: 'Populate auth file with TestDashboard secret'
              shell: bash
              run: |
                  echo ${{ secrets.TEST_DASHBOARD}} > ./TEST_DASHBOARD.txt
                  secretFileSize=$(wc -c "./TEST_DASHBOARD.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing TEST_DASHBOARD secret.";
                      exit 1;
                  fi

            - name: 'Authenticate Test Dashboard'
              run: sfdx auth:sfdxurl:store -f ./TEST_DASHBOARD.txt -a test-dashboard

            - name: 'Run Tests'
              id: run-tests-step
              run: echo "TEST-JOB-ID=$(sfdx force:apex:test:run --testlevel=RunLocalTests --codecoverage --resultformat=json --targetusername=test-dashboard --outputdir=./tests/apex | jq -r '.result.summary.testRunId')" >> $GITHUB_OUTPUT

            - name: 'Echo'
              run: echo "The test job id ${{ steps.run-tests-step.outputs.TEST-JOB-ID }}"

            - name: 'Record Test Run Results'
              run: ./scripts/bash/import-test-result.sh --testrunid ${{ steps.run-tests-step.outputs.TEST-JOB-ID }} --targetusername test-dashboard --sourceusername test-dashboard

            - name: 'Record Test Results'
              run: ./scripts/bash/import-test-run.sh --testrunid ${{ steps.run-tests-step.outputs.TEST-JOB-ID }} --targetusername test-dashboard --sourceusername test-dashboard

            - name: 'Create Scratch Org'
              run: sfdx force:org:create -f config/project-scratch-def.json -a testorg -d 1 -s -v devhub

            - name: 'Install Dependencies'
              run: sfdx force:package:install --package=04t08000000AzzpAAC --wait=30

            - name: 'Deploy Source'
              run: sfdx force:source:push

            - name: 'Delete Scratch Org'
              run: sfdx force:org:delete --targetusername=testorg --noprompt

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
