name: Review
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Clone Repository (Latest)
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.inputs.ref }}

            - name: Code Review
              uses: packocz/sfdx-code-review-action@main
              with:
                  reject_threshold: 3
