name: Review
on:
    workflow_dispatch:
    pull_request:
        types: [opened]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Code Review
              uses: packocz/sfdx-code-review-action@feature/hanlde-all-comments-without-rate-limiting
              with:
                  source_path: 'invest-app/**/*'
                  reject_threshold: 3
                  category: '!Documentation'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
