name: Review
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Clone Repository (Latest)
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.ref }}

            - name: Do git diff
              id: getdiff
              run: echo "::set-output name=difflist::$(git diff --name-only --diff-filter=MCRA $(git merge-base --fork-point ${{ github.base_ref }} ${{ github.sha }})..${{ github.sha }} invest-app/**/* | paste -sd "," -)"

            - name: Install Salesforce CLI
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  mkdir sfdx-cli
                  tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
                  ./sfdx-cli/install

            - name: 'Install Scanner'
              run: sfdx plugins:install @salesforce/sfdx-scanner

            - name: 'Run Scanner'
              run: sfdx scanner:run -t "${{ steps.getdiff.outputs.difflist }}" -f csv > report.csv

            - name: 'Convert report to json'
              run: cat report.csv | python -c 'import csv, json, sys; print(json.dumps([dict(r) for r in csv.DictReader(sys.stdin)]))' > report.json

            - name: 'Transform report to review comments'
              run: |
                  echo "`jq -c 'map({path: ("." + (.File | split("${{ github.event.repository.name }}")[2])), line: (.Line)|tonumber, "start_side": "RIGHT", body: (.Description + " (" + .Engine + "-" + "Severity: " + .Severity + ")")})' report.json`" > comments.json

            - name: Read Comments File
              id: getcomments
              run: echo "::set-output name=comments::$(cat comments.json)"

            - name: 'Create Review'
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/{repo}/pulls/{pull_number}/reviews
                  repo: ${{ github.repository }}
                  pull_number: ${{ github.event.number }}
                  body: 'Static analysis review'
                  event: 'COMMENT'
                  comments: '${{ steps.getcomments.outputs.comments }}'
                  commit_id: ${{ github.sha }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
