name: Review
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Code Review
              uses: packocz/sfdx-code-review-action@main
              with:
                  source_path: 'invest-app/**/*'
                  reject_threshold: 3
                  categoy: '!Documentation'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
